# === Mode & basics ===
mode: paper          # "paper" or "live"
dry_run: false       # if true, forces paper behavior
paper_start_balance: 100.0  # starting base (SOL or USDC) for paper mode accounting
base_asset: "SOL"    # "SOL" or "USDC" (used in sizing & display)

# === Discovery sources ===
discovery:
  birdeye:
    enabled: false
    api_key: ""
    min_liquidity: 5000
    meme_platforms: false
  dexscreener:
    enabled: false            # keep OFF; no public "new pairs" API
    poll_interval: 45
  pump_fun:
    enabled: true             # <- turn ON PumpPortal stream
    websocket_url: "wss://pumpportal.fun/api/data"
  jupiter:
    token_list_check: true
  raydium:
    new_pool_check: false


# === Scoring thresholds ===
scoring:
  min_liquidity: 5000
  max_fdv: 10000000
  max_fdv_liq_ratio: 500
  honeypot_test_amount_sol: 0.05
  max_spread_pct: 5.0
  momentum_window_sec: 300
  momentum_min_change: 0.20

# === Strategies ===
strategies:
  new_listing_snipe:
    enabled: true
    max_age_sec: 120
    slippage: 0.01
    stop_loss_pct: 0.20
    take_profit_pct: 0.50
    trailing_stop_pct: 0.20
  momentum_breakout:
    enabled: true
    min_change_pct: 0.30
    stop_loss_pct: 0.15
    take_profit_layers: [0.50, 1.0]
    trailing_stop_pct: 0.20
  dip_buy:
    enabled: true
    dip_pct: 0.25
    bounce_pct: 0.05
    stop_loss_pct: 0.15
    take_profit_pct: 0.40
    trailing_stop_pct: 0.25

# === Risk management ===
risk:
  capital_base: 100.0
  per_trade_risk_pct: 0.02
  daily_loss_limit_pct: 0.10
  max_drawdown_pct: 0.20
  max_concurrent_trades: 5
  max_trades_per_day: 50

# === Execution ===
execution:
  slippage_tolerance: 0.005
  jupiter:
    base_url: "https://api.jup.ag"
    api_key: ""   # optional
  raydium:
    use_fallback: true
    rpc_endpoint: ""   # required in live mode
  base_mint: "So11111111111111111111111111111111111111112"   # SOL
  quote_mint: "EPjFWdd5AufqSSqe..."    # USDC (fill real mint if using USDC)

# === Logging & alerts ===
logging:
  level: "INFO"
  json: true
  log_file: "logs/tradebot.jsonl"
  trades_csv: "logs/trades.csv"
  discord_webhook: ""
  alerts:
    trade_open: true
    trade_close: true
    risk_events: true

# === Database ===
database:
  path: "tradebot.db"
